//! Raw FFI bindings to libghostty.
//!
//! This `-sys` crate confines every `unsafe` block and every `extern "C"`
//! declaration touching libghostty. Higher-level crates (notably
//! `agent-cockpit-term`) wrap this surface into a safe API and must not
//! contain any `unsafe` of their own. See `README.md` for the rule.

extern "C" {
    // Placeholder. Real bindings are generated by `build.rs` via bindgen in a
    // later step (P1-03) and `include!`d here.
}
