use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use mizraj_vcs::{create_session_ref, repo_open};
use sqlx::SqlitePool;
use tauri::async_runtime::Sender;
use tauri::{AppHandle, Runtime};

use crate::db::Db;
use crate::session::cell_frame::CellFrame;
use crate::session::error::SessionError;
use crate::session::id::SessionId;
use crate::session::key::KeyStroke;
use crate::session::manager::SessionManager;
use crate::session::path;
use crate::session::sink::OutputSink;
use crate::session::tauri_sink::TauriEventSink;
use crate::session::term_sink::TermSink;

fn session_ref_name(session_id: &str) -> String {
    format!("refs/mizraj/sessions/{session_id}")
}

fn register_session_ref(repo_path: &Path, session_id: &str) -> Result<(), SessionError> {
    let repo = repo_open(repo_path).map_err(|err| SessionError::SessionRef(err.to_string()))?;
    create_session_ref(&repo, session_id)
        .map_err(|err| SessionError::SessionRef(err.to_string()))?;
    Ok(())
}

/// Insert the freshly-spawned session row.
///
/// `repo_path` and `worktree_path` are identical until the `wt new` workflow
/// produces a separate worktree; the column split is preserved so later phases
/// can diverge them without a schema change. `started_at` is generated by
/// SQLite (`strftime` with millisecond precision, UTC) so the timestamp lands
/// atomically with the row and we avoid pulling in a date crate.
async fn insert_session_row(
    pool: &SqlitePool,
    id: &SessionId,
    cwd_path: &Path,
) -> Result<(), SessionError> {
    let cwd_str = cwd_path
        .to_str()
        .ok_or_else(|| SessionError::Database(format!("non-utf8 cwd: {}", cwd_path.display())))?;
    let ref_name = session_ref_name(id.as_str());
    sqlx::query(
        "INSERT INTO agent_sessions (id, repo_path, worktree_path, ref_name, started_at, status) \
         VALUES (?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'running')",
    )
    .bind(id.as_str())
    .bind(cwd_str)
    .bind(cwd_str)
    .bind(&ref_name)
    .execute(pool)
    .await
    .map_err(|err| SessionError::Database(err.to_string()))?;
    Ok(())
}

async fn delete_session_row(pool: &SqlitePool, id: &SessionId) -> Result<(), SessionError> {
    sqlx::query("DELETE FROM agent_sessions WHERE id = ?")
        .bind(id.as_str())
        .execute(pool)
        .await
        .map_err(|err| SessionError::Database(err.to_string()))?;
    Ok(())
}

async fn rollback_session_close(manager: &SessionManager, id: &SessionId, context: &str) {
    if let Err(close_err) = manager.session_close(id).await {
        tracing::warn!(
            session_id = id.as_str(),
            error = %close_err,
            context,
            "rollback session_close failed",
        );
    }
}

async fn session_create_inner<F>(
    manager: &SessionManager,
    pool: &SqlitePool,
    binary: &str,
    cwd: String,
    sink_factory: F,
) -> Result<SessionId, SessionError>
where
    F: FnOnce(&SessionId, Sender<Vec<u8>>) -> Vec<Arc<dyn OutputSink>>,
{
    let binary_path = path::resolve(binary)?;
    let cwd_path = PathBuf::from(cwd);
    let env: HashMap<String, String> = HashMap::new();

    let id = manager
        .create_session(binary_path, cwd_path.clone(), env, sink_factory)
        .await?;

    // Insert BEFORE the git ref so rollback only undoes a DB row (cheap,
    // reversible) and a PTY, never a half-written ref.
    if let Err(err) = insert_session_row(pool, &id, &cwd_path).await {
        rollback_session_close(manager, &id, "after db insert error").await;
        return Err(err);
    }

    // Register the session ref so `diff_session` resolves later. If the cwd
    // isn't a git repo or the ref clashes, tear down the just-spawned PTY
    // and delete the row so the diff view never sees a half-wired session.
    if let Err(err) = register_session_ref(&cwd_path, id.as_str()) {
        rollback_session_close(manager, &id, "after session_ref registration error").await;
        if let Err(del_err) = delete_session_row(pool, &id).await {
            tracing::warn!(
                session_id = id.as_str(),
                error = %del_err,
                "rollback DELETE failed after session_ref registration error",
            );
        }
        return Err(err);
    }

    Ok(id)
}

#[tauri::command]
pub async fn session_create<R: Runtime>(
    binary: String,
    cwd: String,
    app: AppHandle<R>,
    manager: tauri::State<'_, SessionManager>,
    db: tauri::State<'_, Db>,
) -> Result<SessionId, SessionError> {
    let pool = db.pool().await.map_err(SessionError::Database)?;
    session_create_inner(&manager, &pool, &binary, cwd, move |id, pty_input| {
        vec![
            Arc::new(TauriEventSink::new(app.clone(), id.clone())) as Arc<dyn OutputSink>,
            Arc::new(TermSink::new(app, id.clone(), pty_input)) as Arc<dyn OutputSink>,
        ]
    })
    .await
}

#[tauri::command]
pub async fn session_resize(
    session_id: SessionId,
    cols: u16,
    rows: u16,
    manager: tauri::State<'_, SessionManager>,
) -> Result<(), SessionError> {
    manager.resize_session(&session_id, cols, rows).await
}

/// VT-encode a key press and write it to the session's PTY. The frontend sends
/// the raw `KeyboardEvent` fields (a [`KeyStroke`]); the backend encodes them
/// with libghostty against the session's live terminal modes, so arrows, Ctrl
/// combos and friends match what the running child expects. The key round-trips
/// to the child and its echo flows back through the normal sink path. Returns
/// `NotFound` for unknown sessions.
#[tauri::command]
pub async fn session_key(
    session_id: SessionId,
    stroke: KeyStroke,
    manager: tauri::State<'_, SessionManager>,
) -> Result<(), SessionError> {
    manager.send_key(&session_id, stroke).await
}

#[tauri::command]
pub async fn session_close(
    session_id: SessionId,
    manager: tauri::State<'_, SessionManager>,
) -> Result<(), SessionError> {
    manager.session_close(&session_id).await
}

/// Pull the session's current grid as a [`CellFrame`] (TP1). A pane invokes
/// this right after subscribing so it paints immediately — even when the
/// session has been idle — instead of staying blank until the next output.
#[tauri::command]
pub async fn session_get_frame(
    session_id: SessionId,
    manager: tauri::State<'_, SessionManager>,
) -> Result<CellFrame, SessionError> {
    manager.request_frame(&session_id).await
}

/// Write raw UTF-8 bytes to the session's PTY, verbatim — the transport for
/// keybind-injected payloads (`text:`/`esc:` actions). Unlike `session_paste`
/// there is no encoding: the binding's bytes ARE the intended input.
#[tauri::command]
pub async fn session_write(
    session_id: SessionId,
    text: String,
    manager: tauri::State<'_, SessionManager>,
) -> Result<(), SessionError> {
    manager.send_input(&session_id, text.into_bytes()).await
}

/// Reset the session's terminal emulator to boot state (Ghostty `reset`
/// keybind action). The child is untouched; the grid repaints fresh.
#[tauri::command]
pub async fn session_reset(
    session_id: SessionId,
    manager: tauri::State<'_, SessionManager>,
) -> Result<(), SessionError> {
    manager.reset_terminal(&session_id).await
}

/// Paste text into the session: the terminal sink encodes it against the live
/// bracketed-paste mode (DEC 2004) and writes it to the PTY (TP7/TP8).
#[tauri::command]
pub async fn session_paste(
    session_id: SessionId,
    text: String,
    manager: tauri::State<'_, SessionManager>,
) -> Result<(), SessionError> {
    manager.paste(&session_id, text.into_bytes()).await
}

/// Mark the session as watched by a frontend pane: the terminal sink resumes
/// emitting `agent:cells` frames (and pushes a catch-up frame if output arrived
/// while hidden). Returns `NotFound` for unknown sessions.
#[tauri::command]
pub async fn session_subscribe(
    session_id: SessionId,
    manager: tauri::State<'_, SessionManager>,
) -> Result<(), SessionError> {
    manager.set_subscribed(&session_id, true).await
}

/// Mark the session as unwatched: the terminal sink stops snapshotting and
/// emitting frames while the grid keeps tracking output (TP3). Returns
/// `NotFound` for unknown sessions.
#[tauri::command]
pub async fn session_unsubscribe(
    session_id: SessionId,
    manager: tauri::State<'_, SessionManager>,
) -> Result<(), SessionError> {
    manager.set_subscribed(&session_id, false).await
}

#[cfg(test)]
mod tests {
    use tauri::async_runtime::block_on;

    use super::*;

    fn fresh_pool() -> sqlx::SqlitePool {
        block_on(crate::db::connect_for_test())
    }

    async fn count_sessions(pool: &sqlx::SqlitePool) -> i64 {
        let (count,): (i64,) = sqlx::query_as("SELECT COUNT(*) FROM agent_sessions")
            .fetch_one(pool)
            .await
            .expect("count agent_sessions");
        count
    }

    fn no_sinks(_: &SessionId, _: Sender<Vec<u8>>) -> Vec<Arc<dyn OutputSink>> {
        Vec::new()
    }

    #[test]
    fn returns_binary_not_found_when_binary_missing() {
        let pool = fresh_pool();
        block_on(async {
            let manager = SessionManager::new();
            let err = session_create_inner(
                &manager,
                &pool,
                "nope-not-a-real-binary-xyz",
                "/tmp".to_string(),
                no_sinks,
            )
            .await
            .expect_err("missing binary should fail");
            match err {
                SessionError::BinaryNotFound(name) => {
                    assert_eq!(name, "nope-not-a-real-binary-xyz");
                }
                other => panic!("expected BinaryNotFound, got {other:?}"),
            }
            // Spawn failure must not leave an orphan row.
            assert_eq!(count_sessions(&pool).await, 0);
        });
    }

    #[test]
    fn binary_not_found_serializes_with_typed_kind() {
        let err = SessionError::BinaryNotFound("claude".into());
        let json = serde_json::to_string(&err).expect("serialize");
        assert_eq!(json, r#"{"kind":"binary_not_found","binary":"claude"}"#);
    }

    #[cfg(target_os = "macos")]
    mod macos {
        use std::fs;
        use std::path::Path;

        use mizraj_vcs::git2::{Repository, RepositoryInitOptions, Signature};
        use tempfile::TempDir;

        use super::*;

        fn init_repo_with_commit(path: &Path) -> Repository {
            let mut opts = RepositoryInitOptions::new();
            opts.external_template(false);
            opts.initial_head("main");
            let repo = Repository::init_opts(path, &opts).expect("init fixture repo");

            let sig = Signature::now("Test", "test@example.com").expect("signature");
            {
                let tree_id = {
                    let mut index = repo.index().expect("index");
                    index.write_tree().expect("write_tree")
                };
                let tree = repo.find_tree(tree_id).expect("find_tree");
                repo.commit(Some("HEAD"), &sig, &sig, "init", &tree, &[])
                    .expect("initial commit");
            }
            repo
        }

        #[test]
        fn spawns_session_and_registers_session_ref() {
            let pool = fresh_pool();
            block_on(async {
                let manager = SessionManager::new();
                let dir = TempDir::new().expect("tempdir");
                init_repo_with_commit(dir.path());

                let id = session_create_inner(
                    &manager,
                    &pool,
                    "sh",
                    dir.path().to_string_lossy().into_owned(),
                    no_sinks,
                )
                .await
                .expect("session_create with /bin/sh should succeed");

                assert_eq!(id.as_str().len(), 26);
                assert!(manager.list_sessions().await.contains(&id));

                let repo = repo_open(dir.path()).expect("repo_open");
                let ref_name = format!("refs/mizraj/sessions/{}", id.as_str());
                repo.find_reference(&ref_name)
                    .expect("session ref should exist after session_create");
            });
        }

        #[test]
        fn rolls_back_spawn_when_cwd_is_not_a_git_repo() {
            let pool = fresh_pool();
            block_on(async {
                let manager = SessionManager::new();
                let dir = TempDir::new().expect("tempdir");
                fs::write(dir.path().join("not-a-repo"), b"").expect("write marker");

                let err = session_create_inner(
                    &manager,
                    &pool,
                    "sh",
                    dir.path().to_string_lossy().into_owned(),
                    no_sinks,
                )
                .await
                .expect_err("non-repo cwd must fail");

                match err {
                    SessionError::SessionRef(_) => {}
                    other => panic!("expected SessionRef, got {other:?}"),
                }

                // Roll back happened: registry is empty.
                assert!(
                    manager.list_sessions().await.is_empty(),
                    "session must be unregistered after ref failure"
                );
                // ref-registration failure must also delete the inserted row.
                assert_eq!(count_sessions(&pool).await, 0);
            });
        }

        #[test]
        fn inserts_running_row_into_agent_sessions() {
            let pool = fresh_pool();
            block_on(async {
                let manager = SessionManager::new();
                let dir = TempDir::new().expect("tempdir");
                init_repo_with_commit(dir.path());
                let cwd = dir.path().to_string_lossy().into_owned();

                let id = session_create_inner(&manager, &pool, "sh", cwd.clone(), no_sinks)
                    .await
                    .expect("session_create should succeed");

                let row: (
                    String,
                    String,
                    String,
                    String,
                    String,
                    String,
                    Option<String>,
                ) = sqlx::query_as(
                    "SELECT id, repo_path, worktree_path, ref_name, started_at, status, ended_at \
                     FROM agent_sessions WHERE id = ?",
                )
                .bind(id.as_str())
                .fetch_one(&pool)
                .await
                .expect("inserted row should be fetchable");

                assert_eq!(row.0, id.as_str());
                assert_eq!(row.1, cwd);
                assert_eq!(row.2, cwd);
                assert_eq!(row.3, format!("refs/mizraj/sessions/{}", id.as_str()));
                assert!(
                    row.4.contains('T') && row.4.ends_with('Z'),
                    "started_at should be ISO 8601 UTC, got {}",
                    row.4
                );
                assert_eq!(row.5, "running");
                assert!(row.6.is_none(), "ended_at should be NULL on insert");
                assert_eq!(count_sessions(&pool).await, 1);
            });
        }
    }
}
