//! The `agent_sessions` row persistence: the data-access seam over the session
//! table, kept apart from the command orchestration so the raw SQL no longer
//! lives on the IPC surface.
use std::path::Path;

use sqlx::SqlitePool;

use crate::session::error::SessionError;
use crate::session::id::SessionId;

fn session_ref_name(session_id: &str) -> String {
    format!("refs/mizraj/sessions/{session_id}")
}

/// Insert the freshly-spawned session row.
///
/// `repo_path` and `worktree_path` are identical until the `wt new` workflow
/// produces a separate worktree; the column split is preserved so later phases
/// can diverge them without a schema change. `started_at` is generated by
/// SQLite (`strftime` with millisecond precision, UTC) so the timestamp lands
/// atomically with the row and we avoid pulling in a date crate.
pub(super) async fn insert_session_row(
    pool: &SqlitePool,
    id: &SessionId,
    cwd_path: &Path,
) -> Result<(), SessionError> {
    let cwd_str = cwd_path
        .to_str()
        .ok_or_else(|| SessionError::Database(format!("non-utf8 cwd: {}", cwd_path.display())))?;
    let ref_name = session_ref_name(id.as_str());
    sqlx::query(
        "INSERT INTO agent_sessions (id, repo_path, worktree_path, ref_name, started_at, status) \
         VALUES (?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), 'running')",
    )
    .bind(id.as_str())
    .bind(cwd_str)
    .bind(cwd_str)
    .bind(&ref_name)
    .execute(pool)
    .await
    .map_err(|err| SessionError::Database(err.to_string()))?;
    Ok(())
}

pub(super) async fn delete_session_row(
    pool: &SqlitePool,
    id: &SessionId,
) -> Result<(), SessionError> {
    sqlx::query("DELETE FROM agent_sessions WHERE id = ?")
        .bind(id.as_str())
        .execute(pool)
        .await
        .map_err(|err| SessionError::Database(err.to_string()))?;
    Ok(())
}
